spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      primary:
        url: jdbc:mysql://localhost:3306/test1?serverTimezone=UTC
        username: root
        password: 1234
      secondary:
        url: jdbc:mysql://localhost:3306/test0?serverTimezone=UTC
        username: root
        password: 1234