call ./myjar sgc 512m GCLogAnalysis2 >> log/aa.txt
call ./myjar pgc 512m GCLogAnalysis2 >> log/aa.txt
call ./myjar cms 512m GCLogAnalysis2 >> log/aa.txt
call ./myjar g1 512m GCLogAnalysis2 >> log/aa.txt
call ./myjar sgc 1g GCLogAnalysis2 >> log/aa.txt
call ./myjar pgc 1g GCLogAnalysis2 >> log/aa.txt
call ./myjar cms 1g GCLogAnalysis2 >> log/aa.txt
call ./myjar g1 1g GCLogAnalysis2 >> log/aa.txt
call ./myjar sgc 2g GCLogAnalysis2 >> log/aa.txt
call ./myjar pgc 2g GCLogAnalysis2 >> log/aa.txt
call ./myjar cms 2g GCLogAnalysis2 >> log/aa.txt
call ./myjar g1 2g GCLogAnalysis2 >> log/aa.txt
call ./myjar sgc 4g GCLogAnalysis2 >> log/aa.txt
call ./myjar pgc 4g GCLogAnalysis2 >> log/aa.txt
call ./myjar cms 4g GCLogAnalysis2 >> log/aa.txt
call ./myjar g1 4g GCLogAnalysis2 >> log/aa.txt